name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js

      - name: Run Linter
        run: pnpm lint

      - name: Run Tests
        run: pnpm test

      - name: Run Build
        run: pnpm build
